train_file:  ['data/vizwiz_train.json']
val_file: 'data/vizwiz_val.json'
test_file: 'data/vizwiz_test.json'
image_root: '/data_src/vizwiz/'

## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False

use_swin: True
image_res: 384
patch_size: 32


## Text Encoder
use_roberta: False
text_config: 'configs/config_bert.json'  # ['configs/config_bert.json', 'configs/config_roberta.json']
text_encoder: 'data/bert-base-uncased'  # ['data/bert-base-uncased', 'data/roberta-base']


## Training
batch_size_train: 12
batch_size_test: 12
batch_size_test_text: 64
max_tokens: 40
embed_dim: 256
temp: 0.07
k_test: 128

## Other Settings
optimizer: {opt: adamW, lr: 5e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 5e-5, epochs: 10, num_warmup_steps: 0.1}

distance: 'wd'  # no, mae, mse, kl, wd
lamda: 0
auto: 0